### ISSUE TITLE
Normalization is run again if IDs are changed

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/bulkRNAseq_MPI_shiny_app#4]
not clear if the normalisation needs to be re-run if only the PlottingIDs or group IDs are changed - not sure if this could be disabled?
I understand that it needs to be run again if samples are un-selected.

**Comment by katsikora** [comment]
That's true that in some cases re-normalization is redundant

I could add some checks such that the identity of included samples as well as the group assignment are unchanged and skip normalization in that case.

On the other hand, the app was designed having certain order of information flow in mind, such that the user inputs the annotation first, and only then the normalization and visualization are performed.
